### ISSUE TITLE
HumanEval shall not be used for training.

### ISSUE THREAD

**Issue by aviczhl2** [sail-sg/Adan#23]
HumanEval is a evaluation dataset, you shouldn't train on it and evaluate on exactly the same dataset. 

Instead, you can use the github part in the Pile, or other coding source data for training. Before training, make sure the training set doesn't contain HumanEval to avoid probable data leakage.

**Comment by XingyuXie** [comment]
Thanks for the kind reminder.

Sorry for the inaccurate description. We indeed pre-trained on the extensive dataset that comes from [BigCode](https://www.bigcode-project.org/); see this [instruction](https://github.com/sail-sg/Adan/tree/main/gpt2) for more details of data processing, and then perform the zero-shot learning on the HumanEval.

Hence we do **NOT** have the data leakage problem because zero-shot learning does not use the evaluation data to learn.
