### ISSUE TITLE
Restarting strategy

### ISSUE THREAD

**Issue by janEbert** [sail-sg/Adan#37]
Hey, the repository does not implement the momentum restarting strategy from what I can tell.

If this is something you still have available, would you be so kind to add it in here? It would be super great to optimize Adan training further. :)

**Comment by XingyuXie** [comment]
We have already provided a function in `adan.py` to reset Momentum, but we do not provide an example of how to use it. We are willing to leave the specific restart conditions for the user to set.

**Comment by janEbert** [comment]
It would be really great for reproducibility of the experiments. Also it would remove redundant work on my side since I'm interested in trying out restarting. Would it maybe be possible to share just the most important snippets?

**Comment by XingyuXie** [comment]
In most experiments, we do not utilize the restart strategy due to convenience. 

From my experience, I try to call the `restart_opt` function first after the warm-up steps and then call it in periodical, like at epoch 50, 100, etc. I found the numerical condition shown in the paper share a similar result with this explicit calling way. 

As I committed in the paper, the reset condition is used for convergence guarantee in the optimization community. Its practical benefits depend on the specific problem.

**Comment by janEbert** [comment]
Thank you for the explanation and sharing your experience with the easy-to-implement way of just calling periodically. :)
The convergence guarantees are intriguing, so I'm still interested in trying it out and see whether my problem benefits. Thank you!
